### ISSUE TITLE
Add GUI buttons for undo and redo

### ISSUE THREAD

**Issue by ordehi** [ordehi/pixelattitude#9]
Undo and redo work by using CTRL + Z and CTRL + Y respectively, but it's a good idea to have GUI buttons to indicate the possibility of undo/redo. This just needs us to attach the undo and redo functions to a couple of buttons.

**Comment by pratham-saraf** [comment]
hey @ordehi 
i am new to open source contribution so can i try it as my first contribution regards. Also can you please point me from where to start regarding this
regards

**Comment by ordehi** [comment]
Hey @pratham-saraf glad to hear you want to contribute! 

If you want to take this, have a read at [CONTRIBUTING.md](https://github.com/ordehi/pixelattitude/blob/main/CONTRIBUTING.md) to get a feel for how to do so, if you've never done this before there's a guide there that shows you the steps you need to take to pull request this.

As by approaching the issue itself, I'd recommend just following the same conventions I'm using for buttons on the header, you could do something with buttons similar to [this line in index.html](https://github.com/ordehi/pixelattitude/blob/2347a2e5d55324de3a4e83fb9a62d12716c11edb/index.html#L62)

The undo and redo functions which you'd be attaching the buttons to stat on [this line in script.js](https://github.com/ordehi/pixelattitude/blob/2347a2e5d55324de3a4e83fb9a62d12716c11edb/script.js#L265).

And one thing that would be nice is to have the buttons show as disabled unless there's something to undo/redo. This is a bonus, but if you want to do it, you could do something with the [writeUndo() and writeRedo() functions](https://github.com/ordehi/pixelattitude/blob/2347a2e5d55324de3a4e83fb9a62d12716c11edb/script.js#L296) to also set the buttons enabled, and disable them in the undo and redo functions by maybe doing a check that [redoStore or redoStore](https://github.com/ordehi/pixelattitude/blob/2347a2e5d55324de3a4e83fb9a62d12716c11edb/script.js#L23) are empty.

Thanks for your interest and nice to e-meet you!

**Comment by pratham-saraf** [comment]
@ordehi i made the respective changes and generated a PR kindly look into it
Thanks

**Comment by ordehi** [comment]
This was closed by @pratham-saraf with [44751331f50b047f6fbbe1e5558b786db69c2c09](https://github.com/ordehi/pixelattitude/commit/44751331f50b047f6fbbe1e5558b786db69c2c09)
